version: "3.8"

services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openresty-proxy
    restart: unless-stopped
    network_mode: host
    environment:
      # Backend configuration
      - BACKEND_HOST=YOUR_BACKEND_IP
      - BACKEND_PORT=80
      - BACKEND_SCHEME=http
      - BACKEND_SSL_NAME=your-domain.com

      # Tech API configuration
      - TECH_API_HOST=127.0.0.1
      - TECH_API_PORT=15000

      # Redis configuration
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379

      # ClickHouse configuration
      - CLICKHOUSE_HOST=127.0.0.1
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DATABASE=logs_db
      - CLICKHOUSE_TABLE=request_logs

      # Performance tuning
      - BATCH_SIZE=1000
      - BATCH_INTERVAL=0.5
      - RPS_LIMIT=60
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/lua:/etc/nginx/lua
      - /etc/letsencrypt/live/your-domain.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/your-domain.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./nginx/logs:/var/log/nginx
      - ./docker-entrypoint.sh:/custom-entrypoint.sh:ro
    command: ["sh", "/custom-entrypoint.sh", "openresty", "-g", "daemon off;"]
    depends_on:
      - redis
      - clickhouse-server

  redis:
    image: redis:latest
    container_name: redis-storage
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: admin
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/config/storage_conf.xml:/etc/clickhouse-server/config.d/storage_conf.xml:ro
      - ./clickhouse/archive:/mnt/clickhouse-archive
      - clickhouse-data:/var/lib/clickhouse

volumes:
  redis-data:
    driver: local
  clickhouse-data:
    driver: local
